export const productos = [
    {
        id: 0,
        nombre: "Comen 2, Pican 4",
        stock: 10,
        descripcion: "Picada comen 2, pican 4 personas",
        precio: 6500,
        contenido: "Tabla de quesos y fiambres: Jamón natural, crudo, lomo ahumado, bondiola, salamín, pategrass, reggianito y azul. Frutos secos y aceitunas rellenas. Degustación de nuestros panificados: Focaccia Italia, Pan de Campo y Chips brioches. Dips para untar.",
        imagen: "/img/picada.jpg",
    },
    {
        id: 1,
        nombre: "Comen 4, Pican 8",
        stock: 10,
        descripcion: "Picada comen 4, pican 8 personas",
        precio: 12800,
        contenido: "Tabla de quesos y fiambres: Jamón natural, crudo, lomo ahumado, bondiola, salamín, pategrass, reggianito y azul. Frutos secos y aceitunas rellenas. Degustación de nuestros panificados: Focaccia Italia, Pan de Campo y Chips brioches. Dips para untar.",
        imagen: "/img/picada2.png",
    },
    {
        id: 2,
        nombre: "Comen 6, Pican 12",
        stock: 10,
        descripcion: "Picada comen 6, pican 12 personas",
        precio: 19000,
        contenido: "Tabla de quesos y fiambres: Jamón natural, crudo, lomo ahumado, bondiola, salamín, pategrass, reggianito y azul. Frutos secos y aceitunas rellenas. Degustación de nuestros panificados: Focaccia Italia, Pan de Campo y Chips brioches. Dips para untar.",
        imagen: "/img/picada.png",
    },
    {
        id: 3,
        nombre: "Brunch Opción 1",
        stock: 10,
        descripcion: "Brunchs",
        precio: 7000,
        contenido: "Sandwich de Lomo y Queso, en Pan de Campo. Scones de Queso y Tomillo. Mini Budines de Naranja y Amapolas. Lingote de Chocotorta. Jugo de Naranja exprimido. Infusiones.",
        imagen: "/img/panes.JPG",
    },
    {
        id: 4,
        nombre: "Brunch Opción 2",
        stock: 10,
        descripcion: "Brunchs",
        precio: 8000,
        contenido: "Bagel de Jamón Crudo y Rúcula. Chipas extra queso. Mini tarta frutal con crema pastelera. Porción de carrot cake. Limonada con menta y jengibre. Infusiones.",
        imagen: "/img/dips.jpg",
    },
    {
        id: 5,
        nombre: "Focaccia Grande",
        stock: 10,
        descripcion: "Panificados",
        precio: 2500,
        imagen: "img/focaccia.jpg",
    },
    {
        id: 6,
        nombre: "Focaccia Chica",
        stock: 10,
        descripcion: "Panificados",
        precio: 1600,
        imagen: "img/focacciaPresentada.jpg",
    },
    {
        id: 7,
        nombre: "Pan de Masa Madre Grande",
        stock: 10,
        descripcion: "Panificados",
        precio: 2500,
        imagen: "img/pan.jpg",
    },
    {
        id: 8,
        nombre: "Pan de Masa Grande Chico",
        stock: 10,
        descripcion: "Panificados",
        precio: 1600,
        imagen: "img/panEnMano.jpg",
    },
    {
        id: 9,
        nombre: "Pre Pizza Napoletana",
        stock: 10,
        descripcion: "Panificados",
        precio: 1000,
        imagen: "img/amasando.JPG",
    },
    {
        id: 10,
        nombre: "Pan Lacteado tipo Artesano",
        stock: 10,
        descripcion: "Panificados",
        precio: 1800,
        imagen: "img/panCortado.jpg",
    },
    {
        id: 11,
        nombre: "Pan Integral Multi Cereal",
        stock: 10,
        descripcion: "Panificados",
        precio: 1800,
        imagen: "img/panCuadrado.jpg",
    },
    {
        id: 12,
        nombre: "Chips Brioche x12",
        stock: 10,
        descripcion: "Panificados",
        precio: 1800,
        imagen: "img/pancitos.jpg",
    },
    {
        id: 13,
        nombre: "Pan de Papa para Hamburguesa x4",
        stock: 10,
        descripcion: "Panificados",
        precio: 1200,
        imagen: "img/panes.JPG",
    },
    {
        id: 14,
        nombre: "Pan de Hamburguesa x4",
        stock: 10,
        descripcion: "Panificados",
        precio: 800,
        imagen: "img/tirandoHarina.jpg",
    },
    {
        id: 15,
        nombre: "Catering",
        stock: 10,
        descripcion: "Catering",
        precio: "Consultar presupuesto",
        contenido: "Mini Hamburguesas caseras con Cheddar. Sliders de Pollo/Carne desmenuzada. Empanaditas de Carne, Pollo, Jamón y Queso. Bruscchetitas caprese/Crudo y Queso. Focaccias con Salsas. Mini Bagels con rellenos varios. Tablitas de quesos y fiambres.",
        imagen: "img/quesos.jpg",
    },
]